version: '3.9'

services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /usr/src/app/mongo:/data/db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    
